-- Create the news table
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    headline TEXT NOT NULL,
    description TEXT,
    content TEXT,
    author TEXT,
    date_published TIMESTAMPTZ DEFAULT NOW(),
    date_modified TIMESTAMPTZ DEFAULT NOW(),
    image TEXT,
    publisher TEXT,
    is_accessible_for_free BOOLEAN DEFAULT TRUE,
    category TEXT,
    slug TEXT UNIQUE
);

-- Enable Row Level Security (RLS)
ALTER TABLE news ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read news
CREATE POLICY "Public news are viewable by everyone" 
ON news FOR SELECT 
USING (true);

-- Create a policy that allows authenticated users (admins) to insert/update/delete
CREATE POLICY "Admins can insert news" 
ON news FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Admins can update news" 
ON news FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Admins can delete news" 
ON news FOR DELETE 
TO authenticated 
USING (true);

-- Seed Data (Mock Data from our Go backend)
INSERT INTO news (headline, description, content, author, date_published, image, publisher, category, slug) VALUES
(
    'Şanlıurfa''da Göbeklitepe Ziyaretçi Rekoru Kırdı',
    'Tarihin sıfır noktası Göbeklitepe, 2024 yılında ziyaretçi akınına uğradı.',
    'Şanlıurfa''nın simgesi haline gelen Göbeklitepe, bu yıl yerli ve yabancı turistlerin ilgi odağı oldu. Yapılan açıklamalara göre...',
    'Ahmet Yılmaz',
    NOW() - INTERVAL '2 days',
    'https://images.unsplash.com/photo-1599576838688-8a6c11263108?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'kultur-sanat',
    'sanliurfa-gobeklitepe-rekor'
),
(
    'Yerli Biber Hasadı Başladı',
    'Şanlıurfa''nın meşhur isot biberi için hasat mevsimi açıldı.',
    'Tarladan sofraya uzanan lezzet yolculuğu başladı. Çiftçiler sabahın erken saatlerinde tarlalara inerek...',
    'Ayşe Demir',
    NOW() - INTERVAL '2 hours',
    'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'ekonomi',
    'yerli-biber-hasadi'
),
(
    'Şanlıurfaspor Deplasmandan 3 Puanla Döndü',
    'Ligin zorlu deplasmanında Şanlıurfaspor altın değerinde 3 puan kazandı.',
    'Maçın başından sonuna kadar üstün bir oyun sergileyen temsilcimiz...',
    'Spor Servisi',
    NOW() - INTERVAL '5 hours',
    'https://images.unsplash.com/photo-1504454138366-407b2f621531?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'spor',
    'sanliurfaspor-galibiyet'
),
(
    'Karaköprü''de Yeni Park Açılışı',
    'Karaköprü Belediyesi tarafından yapılan yeni park törenle hizmete açıldı.',
    'Vatandaşların yoğun ilgi gösterdiği açılışta konuşan Belediye Başkanı...',
    'Mehmet Öztürk',
    NOW() - INTERVAL '1 day',
    'https://images.unsplash.com/photo-1519331379826-f9478558d136?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'gundem',
    'karakopru-park-acilisi'
),
(
    'Harran Üniversitesi''nden Yapay Zeka Hamlesi',
    'Harran Üniversitesi, yapay zeka alanında yeni bir araştırma merkezi kuruyor.',
    'Teknoloji dünyasındaki gelişmeleri yakından takip eden üniversite...',
    'Eğitim Servisi',
    NOW() - INTERVAL '3 days',
    'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'egitim',
    'harran-universitesi-yapay-zeka'
),
(
    'Balıklıgöl''de Çevre Düzenlemesi Başladı',
    'Şanlıurfa''nın en önemli turistik mekanlarından Balıklıgöl''de yenileme çalışmaları.',
    'Ziyaretçilerin daha rahat gezebilmesi için yapılan düzenlemeler...',
    'Kent Haberleri',
    NOW() - INTERVAL '6 hours',
    'https://images.unsplash.com/photo-1541432906375-f4406704308a?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'gundem',
    'balikligol-cevre-duzenlemesi'
),
(
    'Şanlıurfa Mutfağı Dünyaya Tanıtılıyor',
    'Gastronomi şehri Şanlıurfa, lezzetlerini uluslararası arenaya taşıyor.',
    'Düzenlenen fuarda ciğer kebabı, lahmacun ve şıllık tatlısı...',
    'Gurme Yazar',
    NOW() - INTERVAL '12 hours',
    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'yasam',
    'sanliurfa-mutfagi-tanitim'
),
(
    'Pamuk Fiyatları Çiftçiyi Üzdü',
    'Bu yılki pamuk alım fiyatları beklentilerin altında kaldı.',
    'Ziraat Odası tarafından yapılan açıklamada, artan maliyetlere dikkat çekildi...',
    'Ekonomi Masası',
    NOW() - INTERVAL '1 day',
    'https://images.unsplash.com/photo-1593672715438-d88a70629afd?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'ekonomi',
    'pamuk-fiyatlari-ciftci'
),
(
    'Yeni Hastane İnşaatı Hızla Sürüyor',
    'Eyyübiye''de yapımı devam eden şehir hastanesi projesinde sona yaklaşılıyor.',
    'Bölgenin sağlık ihtiyacını karşılayacak olan dev kompleks...',
    'Sağlık Muhabiri',
    NOW() - INTERVAL '4 days',
    'https://images.unsplash.com/photo-1587351021759-3e566b9af923?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'saglik',
    'yeni-hastane-insaati'
),
(
    'Gençlik Merkezleri Yaz Okulları Başlıyor',
    'Şanlıurfa genelindeki gençlik merkezlerinde yaz kursları kayıtları başladı.',
    'Spor, sanat ve kişisel gelişim alanlarında açılacak kurslar...',
    'Gençlik Haber',
    NOW() - INTERVAL '2 days',
    'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1000',
    'UrfadanHaber',
    'egitim',
    'genclik-merkezleri-yaz-okulu'
);
